# Generated by Django 5.2.4 on 2026-01-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО Преподавателя')),
                ('bio', models.TextField(blank=True, verbose_name='О преподавателе')),
                ('expertise', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='registration.teacher', verbose_name='Преподаватель'),
        ),
    ]
