# Generated by Django 5.2.4 on 2026-01-22 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_teacher_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn преподавателя'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (для чего, для кого)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='registration.teacher', verbose_name='Преподаватель'),
        ),
    ]
