# Generated by Django 5.2.4 on 2026-01-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_course_teacher_linkedin_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фото'),
        ),
    ]
