# Generated by Django 5.2.11 on 2026-02-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_alter_enrollment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "⭐ 1 - Плохо"),
                    (2, "⭐⭐ 2 - Так себе"),
                    (3, "⭐⭐⭐ 3 - Нормально"),
                    (4, "⭐⭐⭐⭐ 4 - Хорошо"),
                    (5, "⭐⭐⭐⭐⭐ 5 - Отлично"),
                ],
                default=5,
                verbose_name="Оценка",
            ),
        ),
    ]
